//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLIMPIADAS.Infraestructuras.Datos.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLIMPIADAS.Infraestructuras.Datos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Sqls&gt;
        ///	&lt;Sql&gt;
        ///		&lt;key&gt;GetListaComplejoDeportivo&lt;/key&gt;
        ///		&lt;query&gt;
        ///			Exec ListaComplejoDeportivo
        ///		&lt;/query&gt;
        ///	&lt;/Sql&gt;
        ///&lt;/Sqls&gt;.
        /// </summary>
        internal static string ComplejoDeportivoSql {
            get {
                return ResourceManager.GetString("ComplejoDeportivoSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Sqls&gt;
        ///	&lt;Sql&gt;
        ///		&lt;key&gt;GetListaEquipamientos&lt;/key&gt;
        ///		&lt;query&gt;
        ///			Exec ListaEquipamientos
        ///		&lt;/query&gt;
        ///	&lt;/Sql&gt;
        ///&lt;/Sqls&gt;.
        /// </summary>
        internal static string EquipamientosSql {
            get {
                return ResourceManager.GetString("EquipamientosSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Sqls&gt;
        ///	&lt;Sql&gt;
        ///		&lt;key&gt;GetListaEstados&lt;/key&gt;
        ///		&lt;query&gt;
        ///			Exec ListaEstados
        ///		&lt;/query&gt;
        ///	&lt;/Sql&gt;
        ///&lt;/Sqls&gt;.
        /// </summary>
        internal static string EstadosSql {
            get {
                return ResourceManager.GetString("EstadosSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Sqls&gt;
        ///	&lt;Sql&gt;
        ///		&lt;key&gt;GetLogin&lt;/key&gt;
        ///		&lt;query&gt;EXEC Login &apos;{0}&apos;&lt;/query&gt;
        ///	&lt;/Sql&gt;
        ///&lt;/Sqls&gt;.
        /// </summary>
        internal static string LoginSql {
            get {
                return ResourceManager.GetString("LoginSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Sqls&gt;
        ///	&lt;Sql&gt;
        ///		&lt;key&gt;GetListaSedes&lt;/key&gt;
        ///		&lt;query&gt;
        ///			Exec ListaSedes
        ///		&lt;/query&gt;
        ///	&lt;/Sql&gt;
        ///	&lt;Sql&gt;
        ///		&lt;key&gt;UpdateSedes&lt;/key&gt;
        ///		&lt;query&gt;
        ///			Exec UpdateSedes &apos;{0}&apos;,&apos;{1}&apos;,&apos;{2}&apos;
        ///		&lt;/query&gt;
        ///	&lt;/Sql&gt;
        ///	&lt;Sql&gt;
        ///		&lt;key&gt;DeleteSedes&lt;/key&gt;
        ///		&lt;query&gt;
        ///			Exec DeleteSedes &apos;{0}&apos;
        ///		&lt;/query&gt;
        ///	&lt;/Sql&gt;
        ///&lt;/Sqls&gt;.
        /// </summary>
        internal static string SedesSql {
            get {
                return ResourceManager.GetString("SedesSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Sqls&gt;
        ///	&lt;Sql&gt;
        ///		&lt;key&gt;GetListaComplejoDeportivo&lt;/key&gt;
        ///		&lt;query&gt;
        ///			Exec ListaComplejoDeportivo
        ///		&lt;/query&gt;
        ///	&lt;/Sql&gt;
        ///&lt;/Sqls&gt;.
        /// </summary>
        internal static string TipoComplejosDeportivosSql {
            get {
                return ResourceManager.GetString("TipoComplejosDeportivosSql", resourceCulture);
            }
        }
    }
}
